version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: update-version-dependencies
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: heroku/heroku-buildpack-php
    versions:
    - "188"
    - "189"
    - "190"
  - dependency-name: nesbot/carbon
    versions:
    - 2.43.0
    - 2.45.1
  - dependency-name: laravel/framework
    versions:
    - 7.30.3
  - dependency-name: symfony/polyfill-intl-normalizer
    versions:
    - 1.22.0
  - dependency-name: symfony/yaml
    versions:
    - 5.2.1
  - dependency-name: opis/closure
    versions:
    - 3.6.1
  - dependency-name: league/oauth1-client
    versions:
    - 1.8.2
