[phases.setup]
nixPkgs = ['...', 'nginx']

[phases.install]
cmds = ['mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx', 'composer install', 'npm ci']

[phases.build]
cmds = ['npm run prod']

[phases.release]
cmds = ['php artisan migrate --force']

[phases.start]
cmd ='([ -e /app/storage ] && chmod -R ugo+w /app/storage); echo "Server starting on port $PORT" && php-fpm -y /assets/php-fpm.conf & nginx -c /app/nginx.conf)'
