name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Setup project
      run: make setup
    - name: Check lint
      run: make lint
    - name: Analyse by phpstan
      run: make analyse
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: make test
