name: CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jpribyl/action-docker-layer-caching@v0.1.1

      - name: Run CI
        run: |
          make ci
